#!/bin/sh
# Cloudmorrow installer.  Generated by __BASE_URL__
#
#   curl -fsSL __BASE_URL__/install.sh | sh
#   curl -fsSL __BASE_URL__/install.sh | sh -s -- --agent-token bce_xxx --allow-shell
#
set -eu

CLOUDMORROW_URL="__BASE_URL__"
PACKAGE="__PACKAGE_SPEC__"
AGENT_TOKEN="${CLOUDMORROW_AGENT_TOKEN:-}"
AGENT_NAME=""
ALLOW_SHELL=""
NO_AGENT=""

while [ $# -gt 0 ]; do
	case "$1" in
	--agent-token) AGENT_TOKEN="$2"; shift 2 ;;
	--agent-name) AGENT_NAME="$2"; shift 2 ;;
	--allow-shell) ALLOW_SHELL="--allow-shell"; shift ;;
	--no-agent) NO_AGENT="1"; shift ;;
	--server) CLOUDMORROW_URL="$2"; shift 2 ;;
	-h | --help)
		sed -n '2,8p' "$0" 2>/dev/null || echo "see ${CLOUDMORROW_URL}"
		exit 0
		;;
	*) echo "unknown option: $1" >&2; exit 2 ;;
	esac
done

say() { printf '\033[36m::\033[0m %s\n' "$*"; }
die() { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# --- where to install ------------------------------------------------------
if [ "$(id -u)" = "0" ]; then
	PREFIX="/opt/cloudmorrow"
	BINDIR="/usr/local/bin"
else
	PREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/cloudmorrow"
	BINDIR="$HOME/.local/bin"
fi
VENV="$PREFIX/venv"

# --- python ----------------------------------------------------------------
PYTHON=""
for candidate in python3.14 python3.13 python3.12 python3.11 python3; do
	if command -v "$candidate" >/dev/null 2>&1; then
		if "$candidate" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)' 2>/dev/null; then
			PYTHON="$candidate"
			break
		fi
	fi
done
[ -n "$PYTHON" ] || die "Python 3.11 or newer is required. Install it and run this again."
say "using $($PYTHON -V) at $(command -v "$PYTHON")"

# --- install ---------------------------------------------------------------
say "installing into $VENV"
mkdir -p "$PREFIX" "$BINDIR"
[ -d "$VENV" ] || "$PYTHON" -m venv "$VENV"
"$VENV/bin/python" -m pip install --quiet --upgrade pip
say "fetching $PACKAGE"
# --force-reinstall because the version does not change between commits, so
# plain --upgrade would decide it is already satisfied and skip the new code.
"$VENV/bin/python" -m pip install --quiet --upgrade --force-reinstall "$PACKAGE"

for tool in cloudmorrow cm cloudmorrow-agent; do
	if [ -x "$VENV/bin/$tool" ]; then
		ln -sf "$VENV/bin/$tool" "$BINDIR/$tool"
		say "linked $BINDIR/$tool"
	fi
done

# --- point the CLI at this server -----------------------------------------
"$BINDIR/cloudmorrow" config set api_url "$CLOUDMORROW_URL" >/dev/null
say "CLI configured for $CLOUDMORROW_URL"

# --- optionally enrol the agent -------------------------------------------
if [ -n "$AGENT_TOKEN" ] && [ -z "$NO_AGENT" ]; then
	say "enrolling the local agent"
	set -- --server "$CLOUDMORROW_URL" --token "$AGENT_TOKEN"
	[ -n "$AGENT_NAME" ] && set -- "$@" --name "$AGENT_NAME"
	[ -n "$ALLOW_SHELL" ] && set -- "$@" "$ALLOW_SHELL"
	"$BINDIR/cloudmorrow-agent" enroll "$@"
fi

case ":$PATH:" in
*":$BINDIR:"*) ;;
*) printf '\033[33mnote:\033[0m add %s to your PATH\n' "$BINDIR" ;;
esac

cat <<EOF

  Installed. Next:

    cloudmorrow login              sign in, then
    cloudmorrow                    open the notes TUI  (cm does the same, in two letters)

EOF

if [ -n "$AGENT_TOKEN" ] && [ -z "$NO_AGENT" ]; then
	cat <<EOF
  The agent is enrolled but not running yet. To keep it running:

    linux :  cloudmorrow-agent run          (see ${CLOUDMORROW_URL}/install for a systemd unit)
    macos :  cloudmorrow-agent run

EOF
fi
