#!/bin/sh
# Cloudmorrow installer.  Generated by __BASE_URL__
#
#   curl -fsSL __BASE_URL__/install.sh | sh
#   curl -fsSL __BASE_URL__/install.sh | sh -s -- --agent-token bce_xxx --allow-shell
#   curl -fsSL __BASE_URL__/install.sh | sh -s -- --no-desktop
#
# It installs Cloudmorrow and signs you in, with your own name and password.
# --no-login leaves signing in for later; --server URL is the cloud;
# --dry-run says what it would do, and does none of it.
#
set -eu

CLOUDMORROW_URL="__BASE_URL__"
PACKAGE="__PACKAGE_SPEC__"
# The same, with the desktop app's dependencies: added where there is a desktop.
DESKTOP_PACKAGE="__DESKTOP_PACKAGE_SPEC__"
AGENT_TOKEN="${CLOUDMORROW_AGENT_TOKEN:-}"
AGENT_NAME=""
ALLOW_SHELL=""
NO_AGENT=""
NO_DESKTOP=""
NO_LOGIN=""
DRY_RUN=""

while [ $# -gt 0 ]; do
	case "$1" in
	--agent-token) AGENT_TOKEN="$2"; shift 2 ;;
	--agent-name) AGENT_NAME="$2"; shift 2 ;;
	--allow-shell) ALLOW_SHELL="--allow-shell"; shift ;;
	--no-agent) NO_AGENT="1"; shift ;;
	--no-desktop) NO_DESKTOP="1"; shift ;;
	--no-login) NO_LOGIN="1"; shift ;;
	--dry-run) DRY_RUN="1"; shift ;;
	--server) CLOUDMORROW_URL="$2"; shift 2 ;;
	-h | --help)
		sed -n '2,11p' "$0" 2>/dev/null || echo "see ${CLOUDMORROW_URL}"
		exit 0
		;;
	*) echo "unknown option: $1" >&2; exit 2 ;;
	esac
done

say() { printf '\033[36m::\033[0m %s\n' "$*"; }
note() { printf '\033[33mnote:\033[0m %s\n' "$*"; }
die() { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }
run() {
	if [ -n "$DRY_RUN" ]; then
		printf '   \033[2mwould run:\033[0m %s\n' "$*"
	else
		"$@"
	fi
}

# The released copy of this script (a GitHub Release asset) comes from no
# cloud in particular: the landing page of one runs it with --server. An
# address that is not one is no address.
case "$CLOUDMORROW_URL" in http://* | https://*) ;; *) CLOUDMORROW_URL="" ;; esac
TTY=""
if ( : </dev/tty ) 2>/dev/null; then TTY="/dev/tty"; fi
if [ -z "$CLOUDMORROW_URL" ]; then
	[ -n "$TTY" ] || die "which cloud? run it with --server https://<your cloud>"
	printf 'Your cloud'"'"'s address (https://...): ' >/dev/tty
	read -r CLOUDMORROW_URL </dev/tty || CLOUDMORROW_URL=""
	[ -n "$CLOUDMORROW_URL" ] || die "no address given"
fi
CLOUDMORROW_URL="$(printf '%s' "$CLOUDMORROW_URL" | sed 's|/*$||')"

# --- where to install ------------------------------------------------------
if [ "$(id -u)" = "0" ]; then
	PREFIX="/opt/cloudmorrow"
	BINDIR="/usr/local/bin"
else
	PREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/cloudmorrow"
	BINDIR="$HOME/.local/bin"
fi
VENV="$PREFIX/venv"

# --- python ----------------------------------------------------------------
PYTHON=""
for candidate in python3.14 python3.13 python3.12 python3.11 python3; do
	if command -v "$candidate" >/dev/null 2>&1; then
		if "$candidate" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)' 2>/dev/null; then
			PYTHON="$candidate"
			break
		fi
	fi
done
[ -n "$PYTHON" ] || die "Python 3.11 or newer is required. Install it and run this again."
say "using $($PYTHON -V) at $(command -v "$PYTHON")"

# --- install ---------------------------------------------------------------
say "installing into $VENV"
run mkdir -p "$PREFIX" "$BINDIR"
[ -d "$VENV" ] || run "$PYTHON" -m venv "$VENV"
run "$VENV/bin/python" -m pip install --quiet --upgrade pip
say "fetching $PACKAGE"
# --force-reinstall because the version does not change between commits, so
# plain --upgrade would decide it is already satisfied and skip the new code.
run "$VENV/bin/python" -m pip install --quiet --upgrade --force-reinstall "$PACKAGE"

for tool in cloudmorrow cm cloudmorrow-agent; do
	if [ -x "$VENV/bin/$tool" ] || [ -n "$DRY_RUN" ]; then
		run ln -sf "$VENV/bin/$tool" "$BINDIR/$tool"
		say "linked $BINDIR/$tool"
	fi
done

# --- point the CLI at this server -----------------------------------------
# The server this script came from. Without it, `cloudmorrow login` would
# look on the home network and list the clouds it finds there instead.
run "$BINDIR/cloudmorrow" config set api_url "$CLOUDMORROW_URL" >/dev/null
say "CLI configured for $CLOUDMORROW_URL"

# --- the desktop app, where there is a desktop -----------------------------
# The web app in a window of its own, which also mounts your shares on this
# computer: `cloudmorrow app`. Only for a person at a graphical session — a
# machine reached over ssh, a server or a root install gets the terminal app
# alone, as before. The extra is installed on top of what is already there,
# without --force-reinstall, so running this again does not fetch Qt again.
DESKTOP=""
if [ -n "$NO_DESKTOP" ]; then
	say "skipping the desktop app (--no-desktop)"
elif [ "$(id -u)" = "0" ]; then
	: # a root install is for every user and none of them in particular
elif [ -n "$DRY_RUN" ]; then
	say "would add the desktop app, if a desktop is running here"
elif [ "$(uname -s)" = "Linux" ]; then
	if [ -n "${WAYLAND_DISPLAY:-}" ] || [ -n "${DISPLAY:-}" ]; then
		say "a desktop is running here: adding the desktop app (this is the big download)"
		if "$VENV/bin/python" -m pip install --quiet "$DESKTOP_PACKAGE" \
			&& "$BINDIR/cloudmorrow" app --install-launcher; then
			DESKTOP="1"
			say "Cloudmorrow is in your applications menu"
		else
			note "the desktop app did not install; the terminal app is fine"
		fi
	fi
fi
# TODO(macos): the extra installs on a Mac as it is (pywebview uses the
# system's WKWebView there), but there is no launcher yet: that needs an .app
# bundle in ~/Applications that runs `cloudmorrow app` — see
# cloudmorrow/desktop/launcher.py. Until it exists a Mac gets the terminal app,
# and `pip install 'cloudmorrow[desktop]'` into $VENV by hand for the window.
# TODO(windows): this script does not run on Windows; that needs a
# PowerShell installer that makes the venv and a Start-menu shortcut.

# --- optionally enrol the agent -------------------------------------------
if [ -n "$AGENT_TOKEN" ] && [ -z "$NO_AGENT" ]; then
	say "enrolling the local agent"
	set -- --server "$CLOUDMORROW_URL" --token "$AGENT_TOKEN"
	[ -n "$AGENT_NAME" ] && set -- "$@" --name "$AGENT_NAME"
	[ -n "$ALLOW_SHELL" ] && set -- "$@" "$ALLOW_SHELL"
	run "$BINDIR/cloudmorrow-agent" enroll "$@"
fi

# --- signing in ------------------------------------------------------------
# `cloudmorrow login` asks for the name and password. Asked on the terminal,
# not stdin: through `curl | sh`, stdin is this script.
SIGNED_IN=""
if [ -z "$NO_LOGIN" ]; then
	if [ -n "$DRY_RUN" ]; then
		run "$BINDIR/cloudmorrow" login --server "$CLOUDMORROW_URL"
	elif [ -n "$TTY" ]; then
		say "signing in to $CLOUDMORROW_URL"
		if "$BINDIR/cloudmorrow" login --server "$CLOUDMORROW_URL" </dev/tty; then
			SIGNED_IN="1"
		else
			note "not signed in; afterwards: cloudmorrow login"
		fi
	fi
fi

case ":$PATH:" in
*":$BINDIR:"*) ;;
*) note "add $BINDIR to your PATH" ;;
esac

cat <<EOF

  Installed. Next:

EOF
if [ -z "$SIGNED_IN" ]; then
	cat <<EOF
    cloudmorrow login              sign in, then
EOF
fi
cat <<EOF
    cloudmorrow                    open the notes TUI  (cm does the same, in two letters)

  With no server set, \`cloudmorrow login\` lists the clouds it finds on
  your home network.

EOF

if [ -n "$DESKTOP" ]; then
	cat <<EOF
  The desktop app is in your applications menu, or:

    cloudmorrow app                the web app in a window, mounting shares here

EOF
fi

if [ -n "$AGENT_TOKEN" ] && [ -z "$NO_AGENT" ]; then
	cat <<EOF
  The agent is enrolled but not running yet. To keep it running:

    linux :  cloudmorrow-agent run          (see ${CLOUDMORROW_URL}/install for a systemd unit)
    macos :  cloudmorrow-agent run

EOF
fi
