"""PostgreSQL: the other engine. A server of its own, a pool of connections.

For the person who already runs one, for a cloud too large for one file,
and for the day the server runs as several processes. What is PostgreSQL's
alone lives here: the pool, `%s` placeholders behind the `?` every store
writes, the version in a table of its own, `ctid`, `->>` and a `jsonb`
column, and an advisory lock for "take the write lock".

The driver is psycopg 3, which the `postgres` extra brings; this module is
imported only when a `postgresql://` URL is opened.
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterable, Sequence
from functools import lru_cache
from typing import Any

import psycopg
from psycopg.types.string import TextLoader
from psycopg_pool import ConnectionPool, PoolTimeout

from cloudmorrow.server.database import (
    DatabaseError,
    Dialect,
    Engine,
    IntegrityError,
    OperationalError,
)

# How many connections one process keeps to the server. The request
# threads share them; one waiting for a free one waits POOL_WAIT seconds.
POOL_SIZE = 16
POOL_WAIT = 30.0
# The one advisory lock that is "the write lock": what BEGIN IMMEDIATE is on
# SQLite. Any number; this one is ours.
LOCK_KEY = 0x636D7772  # "cmwr"


class Row:
    """A row by column name, by index, by slice, as a store reads one."""

    __slots__ = ("_index", "_values")

    def __init__(self, index: dict[str, int], values: Sequence[Any]) -> None:
        self._index = index
        self._values = tuple(values)

    def __getitem__(self, key: int | str | slice) -> Any:
        if isinstance(key, str):
            try:
                return self._values[self._index[key]]
            except KeyError:
                raise IndexError(f"no such column: {key}") from None
        return self._values[key]

    def keys(self) -> list[str]:
        return list(self._index)

    def __iter__(self) -> Any:
        return iter(self._values)

    def __len__(self) -> int:
        return len(self._values)

    def __eq__(self, other: object) -> bool:
        return tuple(self) == tuple(other) if isinstance(other, Row | tuple) else NotImplemented

    def __hash__(self) -> int:
        return hash(self._values)

    def __repr__(self) -> str:
        return f"Row({dict(zip(self._index, self._values, strict=False))!r})"


def _rows(cursor: psycopg.Cursor) -> Any:
    description = cursor.description or ()
    index = {column.name: position for position, column in enumerate(description)}
    return lambda values: Row(index, values)


@lru_cache(maxsize=1024)
def _placeholders(sql: str) -> str:
    """`?` to `%s`, outside quotes; `%` doubled, since the driver reads it."""
    out: list[str] = []
    quoted = False
    for char in sql:
        if char == "'":
            quoted = not quoted
            out.append(char)
        elif quoted:
            out.append(char)
        elif char == "?":
            out.append("%s")
        elif char == "%":
            out.append("%%")
        else:
            out.append(char)
    return "".join(out)


class PostgresDialect(Dialect):
    name = "postgres"
    row_address = "ctid"

    def ddl(self, sql: str) -> str:
        sql = re.sub(
            r"\bINTEGER PRIMARY KEY AUTOINCREMENT\b", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql
        )
        sql = re.sub(r"^(\s*\w+\s+)JSON\b", r"\1JSONB", sql, flags=re.MULTILINE)
        return re.sub(r"\bINTEGER AUTONUMBER\b", "BIGINT GENERATED BY DEFAULT AS IDENTITY", sql)

    def json_text(self, column: str, field: str) -> str:
        return f"({column}->>'{field}')"

    def json_compare(self, column: str, field: str, op: str, value: object) -> tuple[str, list[object]]:
        if op.upper() == "IS":
            op = "IS NOT DISTINCT FROM"
        if isinstance(value, bool | int | float):
            # Typed, against the JSON value itself: a number is a number
            # and true is true, as json_extract has it on SQLite.
            return f"({column}->'{field}') {op} ?::jsonb", [json.dumps(value)]
        return f"{self.json_text(column, field)} {op} ?", [value]

    def next_number(self, table: str, column: str) -> str:
        return "DEFAULT"


class PostgresEngine(Engine):
    name = "postgres"
    dialect = PostgresDialect()
    checks_every_connect = False

    def __init__(self, url: str) -> None:
        self.url = url
        self._pool: ConnectionPool | None = None

    def _pooled(self) -> ConnectionPool:
        if self._pool is None:
            self._pool = ConnectionPool(
                self.url,
                min_size=1,
                max_size=POOL_SIZE,
                timeout=POOL_WAIT,
                kwargs={"row_factory": _rows, "cursor_factory": psycopg.ClientCursor},
                configure=_configure,
                open=True,
            )
        return self._pool

    def acquire(self) -> psycopg.Connection:
        try:
            return self._pooled().getconn()
        except (psycopg.Error, PoolTimeout) as exc:
            raise OperationalError(f"cannot reach the database at {self.url.split('@')[-1]}: {exc}") from exc

    def release(self, raw: psycopg.Connection) -> None:
        if self._pool is None:
            raw.close()
            return
        try:
            if raw.info.transaction_status != psycopg.pq.TransactionStatus.IDLE:
                raw.rollback()
        finally:
            self._pool.putconn(raw)

    def close(self) -> None:
        pool, self._pool = self._pool, None
        if pool is not None:
            pool.close()

    def prepare(self, raw: psycopg.Connection) -> None:
        # The version table, made under the lock so two processes starting
        # together make it once. Nothing in it means version 0.
        self.lock(raw)
        raw.execute("CREATE TABLE IF NOT EXISTS schema_version (version INTEGER NOT NULL)")
        raw.execute("INSERT INTO schema_version (version) SELECT 0 WHERE NOT EXISTS (SELECT 1 FROM schema_version)")
        raw.commit()

    def execute(self, raw: psycopg.Connection, sql: str, params: Sequence[object]) -> psycopg.Cursor:
        cursor = raw.cursor()
        if params:
            cursor.execute(_placeholders(sql), tuple(params))
        else:
            cursor.execute(sql)
        return cursor

    def executemany(self, raw: psycopg.Connection, sql: str, rows: Iterable[Sequence[object]]) -> None:
        raw.cursor().executemany(_placeholders(sql), [tuple(row) for row in rows])

    def executescript(self, raw: psycopg.Connection, script: str) -> None:
        raw.execute(script)

    def insert(self, raw: psycopg.Connection, sql: str, params: Sequence[object], key: str) -> int:
        cursor = self.execute(raw, f"{sql} RETURNING {key}", params)
        return int(cursor.fetchone()[0])

    def lock(self, raw: psycopg.Connection) -> None:
        raw.execute(f"SELECT pg_advisory_xact_lock({LOCK_KEY})")

    def schema_version(self, raw: psycopg.Connection) -> int:
        row = raw.execute("SELECT version FROM schema_version").fetchone()
        return int(row[0]) if row else 0

    def set_schema_version(self, raw: psycopg.Connection, version: int) -> None:
        raw.execute("UPDATE schema_version SET version = %s", (int(version),))

    def table_exists(self, raw: psycopg.Connection, name: str) -> bool:
        row = raw.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = %s",
            (name,),
        ).fetchone()
        return row is not None

    def columns(self, raw: psycopg.Connection, table: str) -> set[str]:
        rows = raw.execute(
            "SELECT column_name FROM information_schema.columns"
            " WHERE table_schema = current_schema() AND table_name = %s",
            (table,),
        ).fetchall()
        return {row[0] for row in rows}

    def in_transaction(self, raw: psycopg.Connection) -> bool:
        return raw.info.transaction_status != psycopg.pq.TransactionStatus.IDLE

    def translate(self, exc: BaseException) -> DatabaseError | None:
        if isinstance(exc, psycopg.IntegrityError):
            return IntegrityError(str(exc))
        if isinstance(exc, psycopg.OperationalError | psycopg.errors.UndefinedTable):
            return OperationalError(str(exc))
        if isinstance(exc, psycopg.Error):
            return DatabaseError(str(exc))
        return None


def _configure(raw: psycopg.Connection) -> None:
    # A JSON column reads back as the text that was written, as it does on
    # SQLite: the store parses it, the driver does not.
    raw.adapters.register_loader("jsonb", TextLoader)
    raw.adapters.register_loader("json", TextLoader)
