#!/usr/bin/env python3
"""The client installer as a release asset: install.sh for no cloud in particular.

A cloud serves its own installer at `/install.sh`, with its address and its
package baked in (server/routes/install.py). Somebody who has no cloud's
page open gets this one instead, from the latest GitHub Release,

    https://github.com/Cloudmorrow/cloudmorrow/releases/latest/download/install.sh

and runs it with `--server https://<their cloud>`. So this is the same
template with the package pointed at the wheel published beside it in the
same release, and no address: the script asks for one when --server is not
given.

    python scripts/release_installer.py --tag v0.13.0 \\
        --wheel dist/cloudmorrow-0.13.0-py3-none-any.whl --out dist/install.sh

Run by the release workflow (.github/workflows/release.yml).
"""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "src" / "cloudmorrow" / "server" / "templates" / "install.sh"
REPOSITORY = "https://github.com/Cloudmorrow/cloudmorrow"
# What the comments at the top show where a served copy has its cloud's address.
EXAMPLE = "https://<your cloud>"


def render(tag: str, wheel: str, repository: str = REPOSITORY) -> str:
    url = f"{repository}/releases/download/{tag}/{wheel}"
    text = TEMPLATE.read_text(encoding="utf-8")
    text = text.replace(
        "# Cloudmorrow installer.  Generated by __BASE_URL__",
        f"# Cloudmorrow installer, released with {tag}. Give it your cloud with --server.",
    )
    text = text.replace('CLOUDMORROW_URL="__BASE_URL__"', 'CLOUDMORROW_URL=""')
    text = text.replace("__BASE_URL__", EXAMPLE)
    # PEP 508 direct references, as a cloud with a published wheel serves them.
    text = text.replace("__DESKTOP_PACKAGE_SPEC__", f"cloudmorrow[tui,agent,desktop] @ {url}")
    text = text.replace("__PACKAGE_SPEC__", f"cloudmorrow[tui,agent] @ {url}")
    return text


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--tag", required=True, help="The release's tag: v0.13.0.")
    parser.add_argument("--wheel", required=True, help="The wheel published in the same release.")
    parser.add_argument("--out", default="dist/install.sh")
    parser.add_argument("--repository", default=REPOSITORY)
    args = parser.parse_args()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(args.tag, Path(args.wheel).name, args.repository), encoding="utf-8")
    out.chmod(0o755)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
